### ISSUE TITLE
the input image size for classifier

### ISSUE THREAD

**Issue by rener1199** [toshi-k/kaggle-distracted-driver-detection#1]
After detector step, we can get a cropped image which was the input of the classifier,but the size is not fixed after segmentation,if we just do a resize such as 224x224, the image is changed! So do you think the segmentation step is very important for your task? How do you deal with image size problem?

**Comment by toshi-k** [comment]
I crop and resize images before classification step.
@function load_with_mask(file_path, mask_path)
https://github.com/toshi-k/kaggle-distracted-driver-detection/blob/master/source/02_classifier/1_data.lua

Segmentation step was important to compete with other people. However, you may get enough accuracy without segmentation. You can throw original image to classifier too.
